/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 s24.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/s24.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.292, 0.467, -0.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, 0.114]}>
        <mesh geometry={nodes.Object_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials.Silver} />
        <mesh geometry={nodes.Object_0_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_0_3.geometry} material={materials.Flash} />
        <mesh geometry={nodes.Object_0_4.geometry} material={materials.Lens} />
        <mesh geometry={nodes.Object_0_5.geometry} material={materials.Screen} />
      </group>
      <mesh geometry={nodes.screen.geometry} material={materials.Screen} position={[0.292, 0.467, -0.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, 0.114]} />
    </group>
  )
}

useGLTF.preload('/s24.gltf')
